alter table PLANETS_ATMOSPHERE add constraint FK_PLANETS_ATMOSPHERE_ON_PLANET foreign key (PLANET_ID) references PLANETS_PLANET(ID);
create index IDX_PLANETS_ATMOSPHERE_ON_PLANET on PLANETS_ATMOSPHERE (PLANET_ID);
