alter table PLANETS_ATMOSPHERE alter column ATMOSPHERE_ID rename to ATMOSPHERE_ID__U27431 ^
alter table PLANETS_ATMOSPHERE drop constraint FK_PLANETS_ATMOSPHERE_ON_ATMOSPHERE ;
drop index IDX_PLANETS_ATMOSPHERE_ON_ATMOSPHERE ;
